### PR TITLE
Implement pallet-halving-mint

### PR DESCRIPTION
**Pull request by Kailai-Wang**
This is a simple pallet to mint native tokens in a halving way, similar to BTC.

The `TotalIssuance` and `HalvingInterval` are provided as runtime constants.
The tokens will be minted to a beneficiary account (usually a pallet acount which no one has private key) and there's a OnTokenMinted hook for callbacks in other pallets.

No benchmarking / WeightInfo yet as I don't think that's as important - the extrinsics are not complicated and expected to be called only once/few times.

### CODE REVIEW

**Review by felixfaisal — APPROVED** [review]
Thanks @Kailai-Wang 
The halving logic looks straightforward and I have nothing to complain. 
However I'm wondering if using a halving mint is the right way to go: 
1. We are not taking into consideration the network activity when reducing the reward amount (I'm assuming mint will be used for reward), So we should consider the staking activity when adjusting the amount of rewards. 
2. It would be much better if we let governance/stakers adjust the the reward parameters  because they are in fact the biggest stake holders. 
3. We can use the existing `staking` pallet and use reward-curve to setup a gradual decay in the rewards amount as the network activity increases. This way we don't have to setup our own custom pallet thereby reducing the development time. 
4. However 1,2,3 is only if the minted tokens is used as rewards, But if this is the total tokens that are being unlocked linearly then it would make it difficult to list and bridge tokens from other exchanges and chains. 

I think I am clearly missing something from the requirement itself 😅 . Let me know what you think, it would be nice to have a clear idea on how this will be a part of the greater staking pool implementation.

**Comment by Kailai-Wang** [comment]
Thanks @felixfaisal 

I don't fully understand your questions though - like how is this pallet related to the network activities and staking rewards. This pallet simply mints tokens with gradually reduced interval, similar to btc. The rewards (minted tokens) are paid on a block basis, to the beneficiary account.

I mean "halving mint" is the requirement of how the CAN tokens should be issued, regardless of how they are used. At least that's what I got 😂 

Could you elaborate the concerns a bit, please?

**Comment by felixfaisal** [comment]
> Thanks @felixfaisal
> 
> I don't fully understand your questions though - like how is this pallet related to the network activities and staking rewards. This pallet simply mints tokens with gradually reduced interval, similar to btc. The rewards (minted tokens) are paid on a block basis, to the beneficiary account.
> 
> I mean "halving mint" is the requirement of how the CAN tokens should be issued, regardless of how they are used. At least that's what I got 😂
> 
> Could you elaborate the concerns a bit, please?

I was confused with the requirement 😅 , I think it makes sense now

**Comment by wangminqi** [comment]
Can you temporarily keep pallet_template? I think it will be more convenient for some testing purpose. Like precompile.

**Pull request merged**
